# Generated by Django 5.2 on 2025-08-29 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='balls',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='registered_game',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('CRICKET', 'Cricket')], default='FOOTBALL', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINAL', 'Final')], default='SCHEDULED', max_length=12),
        ),
        migrations.AddField(
            model_name='game',
            name='team1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_led', to='games.player'),
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='games.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.team')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='games_playe_game_id_e0a3f0_idx'), models.Index(fields=['player'], name='games_playe_player__297e09_idx')],
                'unique_together': {('game', 'player')},
            },
        ),
    ]
