# Generated by Django 5.2 on 2025-08-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_player_balls_remove_player_kills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricket',
            name='batting_side',
            field=models.CharField(choices=[('TEAM1', 'Team 1'), ('TEAM2', 'Team 2')], default='TEAM1', max_length=6),
        ),
        migrations.AddField(
            model_name='cricket',
            name='current_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batsman_in', to='games.player'),
        ),
        migrations.AddField(
            model_name='cricket',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bowler_in', to='games.player'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('CRICKET', 'Cricket')], max_length=16)),
                ('points', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wicket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='games.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_events', to='games.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='games.team')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'created_at'], name='games_score_game_id_7eaae8_idx'), models.Index(fields=['team', 'created_at'], name='games_score_team_id_d56b11_idx')],
            },
        ),
    ]
