# Generated by Django 5.2 on 2025-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreevent',
            name='batting_side',
            field=models.CharField(blank=True, choices=[('TEAM1', 'Team 1'), ('TEAM2', 'Team 2')], max_length=6, null=True),
        ),
    ]
