# Generated by Django 5.2.6 on 2025-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_basketball_actual_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
