# Generated by Django 5.2.6 on 2025-09-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='games.basketball')),
            ],
        ),
    ]
