# Generated by Django 5.2.6 on 2025-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_basketballstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball',
            name='quarter1_finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketball',
            name='quarter2_finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketball',
            name='quarter3_finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketball',
            name='quarter4_finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
