# Generated by Django 5.2.6 on 2025-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_basketball_quarter1_finished_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball',
            name='team1_active_players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'team__team1_games__isnull': False}, related_name='team1_active_in_basketball', to='games.player'),
        ),
        migrations.AddField(
            model_name='basketball',
            name='team2_active_players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'team__team2_games__isnull': False}, related_name='team2_active_in_basketball', to='games.player'),
        ),
    ]
